import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Solbrew Spin the Wheel",
  description: "Generated by beer for beer",
  icons: {
    icon: '/favicon.ico', // Reference favicon in public/
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
