# netlify.toml
[build]
  command = "npm run build"
  publish = "solbrew-spinly/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200